// Generated by CoffeeScript 1.8.0
var arr;

arr = ["./libs/jquery.js", "./libs/sugar.js", "./libs/oj.js", "./libs/easings.js", "./libs/dirty.js"];

head.js.apply(this, arr);

head(function() {
  var render_audio, render_video;
  oj.useGlobally();
  render_video = function(name, size) {
    if (size == null) {
      size = 720;
    }
    name = "../assets/builds/" + name + size;
    return video({
      poster: "" + name + ".png",
      controls: false,
      autoplay: true,
      loop: false
    }, function() {
      source({
        src: "" + name + ".mp4"
      });
      source({
        src: "" + name + ".webm"
      });
      return p(function() {
        return "video unsupported on your browser";
      });
    });
  };
  render_audio = function(name) {
    name = "../assets/builds/" + name;
    return audio({
      controls: false,
      autoplay: false,
      loop: false
    }, function() {
      source({
        src: "" + name + ".mp3"
      });
      source({
        src: "" + name + ".ogg"
      });
      return p(function() {
        return "audio unsupported on your browser";
      });
    });
  };
  return $("#main").oj(div(function() {
    h2({
      style: "color:grey; font-size:28px; padding:0px; margin:0px;"
    }, function() {
      return "hi der!";
    });
    render_audio("dylanleslie_slow_jam");
    return render_video("shakey_spring", 480);
  }));
});

//# sourceMappingURL=index.js.map
